version: '3'

services:
  django-app:
    container_name: django-app
    build: ./example_project
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./example_project:/app
    ports:
      - "8000:8000"
    env_file:
     - ./env_variables/django_app.env
    depends_on:
     - db

  db:
    image: postgres
    restart: always
    env_file:
      - ./env_variables/db.env
    volumes:
      - db_data:/var/lib/postgresql/data


  telegraf:
    image: telegraf
    container_name: telegraf
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf
    depends_on:
      - django-app
      - influxdb
    links:
      - influxdb
    ports:
    - '8125:8125'

  influxdb:
    image: influxdb:1.8
    container_name: influxdb
    restart: always
    env_file:
      - ./env_variables/influxdb.env
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

  grafana:
    image: grafana/grafana
    container_name: grafana-server
    restart: always
    depends_on:
      - influxdb
    env_file:
     - ./env_variables/grafana.env
    links:
      - influxdb
    ports:
      - '3000:3000'
    volumes:
      - grafana_data:/var/lib/grafana



volumes:
  db_data:
  influxdb_data:
  grafana_data:
